In [1]:
import requests

In [85]:
offset_ = 7001
limit_ = 4000
url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/kn/object?offset={offset_}&limit={limit_}&sortField=devId.devShortCleanNm&sortType=asc&objStatus=0'
res = requests.get(url)
objects_data = res.json()
objects_data.get('data').get('list')[0]

{'objId': 13391,
 'developer': {'devId': 306,
  'shortName': '2МЕН ГРУПП',
  'fullName': '2МЕН ГРУПП',
  'groupName': '2МЕН ГРУПП ДЕВЕЛОПМЕНТ',
  'orgForm': {'id': 1, 'fullForm': 'Акционерное общество', 'shortForm': 'АО'},
  'companyGroup': 5776,
  'devInn': '7701651356'},
 'rpdRegionCd': 72,
 'objAddr': 'г Тюмень, ул Профсоюзная',
 'objFloorMin': 3,
 'objFloorMax': 12,
 'objElemLivingCnt': 44,
 'objReady100PercDt': '2022-12-31',
 'objSquareLiving': 4297.44,
 'objCompensFundFlg': 1,
 'objProblemFlg': 0,
 'latitude': 57.1541,
 'longitude': 65.5595,
 'problemFlag': 'NONE',
 'siteStatus': 'Строящиеся',
 'objGuarantyEscrowFlg': 0,
 'residentialBuildings': 1,
 'rpdNum': '72-000096',
 'pdId': 28101,
 'buildType': 'Жилое',
 'objStatus': 0}

In [86]:
objects_list = objects_data.get('data').get('list')
objids = [x.get('objId') for x in objects_list]
objids[:10]

[13391, 13397, 13398, 13399, 13383, 36912, 44076, 23494, 27476, 10891]

In [87]:
url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/object/29679'

In [88]:
res = requests.get(url)
d = res.json()

In [89]:
import pandas as pd
from tqdm.auto import tqdm

In [90]:
d = []
for obj in tqdm(objids):
        url = f'https://xn--80az8a.xn--d1aqf.xn--p1ai/%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D1%8B/api/object/{obj}'
        res = requests.get(url)
        d.append(res.json())

  0%|          | 0/3000 [00:00<?, ?it/s]

In [91]:
len(d)

3000

In [92]:
df1 = pd.json_normalize(d)
df1

,errcode,data.id,data.pdId,data.developer.devId,data.developer.devShortCleanNm,data.developer.devShortNm,data.developer.devFullCleanNm,data.developer.problObjCnt,data.developer.buildObjCnt,data.developer.comissObjCnt,...,data.developer.bankruptStage.bankruptStageDesc,data.developer.bankruptStage.bankruptLawUrl,data.developer.orgBankruptMsgDttm,data.metro.id,data.metro.name,data.metro.line,data.metro.color,data.metro.time,data.metro.isWalk,data.metro.colors
0,0,13391,28101,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,13397,28141,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,13398,28141,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,13399,28141,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,13383,28105,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0,44809,553544,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,0,44811,553544,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,0,44812,553544,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,0,44820,553544,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,0,44821,553544,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
df3 = pd.json_normalize(d)
df3

,errcode,data.id,data.pdId,data.developer.devId,data.developer.devShortCleanNm,data.developer.devShortNm,data.developer.devFullCleanNm,data.developer.problObjCnt,data.developer.buildObjCnt,data.developer.comissObjCnt,...,data.metro.color,data.metro.time,data.metro.isWalk,data.metro.colors,data.greenAreaIndexValue,data.airQualityIndexValue,data.developer.bankruptStage.bankruptStageCd,data.developer.bankruptStage.bankruptStageDesc,data.developer.bankruptStage.bankruptLawUrl,data.developer.orgBankruptMsgDttm
0,0,44871,539340,1010,СЗ СИТИ ПРОЕКТ,СЗ СИТИ ПРОЕКТ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СИТИ ПРОЕКТ,0,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,43647,526234,11176,СЗ СИТИ-ТРЕЙД,СЗ СИТИ-ТРЕЙД,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СИТИ-ТРЕЙД,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,37882,384236,6646,СЗ СК АЙ КЬЮ ДЕВЕЛОПМЕНТ,СЗ СК АЙ КЬЮ ДЕВЕЛОПМЕНТ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СК АЙ КЬЮ ДЕВЕЛО...,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,41611,472616,6646,СЗ СК АЙ КЬЮ ДЕВЕЛОПМЕНТ,СЗ СК АЙ КЬЮ ДЕВЕЛОПМЕНТ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СК АЙ КЬЮ ДЕВЕЛО...,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,45819,562549,6646,СЗ СК АЙ КЬЮ ДЕВЕЛОПМЕНТ,СЗ СК АЙ КЬЮ ДЕВЕЛОПМЕНТ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СК АЙ КЬЮ ДЕВЕЛО...,0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3585,0,28071,99284,7344,ЯРКИЙ МИР,ЯРКИЙ МИР,ЯРКИЙ МИР,0,5,0,...,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN
3586,0,28074,96537,7344,ЯРКИЙ МИР,ЯРКИЙ МИР,ЯРКИЙ МИР,0,5,0,...,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN
3587,0,28072,96379,7344,ЯРКИЙ МИР,ЯРКИЙ МИР,ЯРКИЙ МИР,0,5,0,...,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN
3588,0,44447,475093,2538,ЯРОСЛАВЛЬЗАКАЗЧИК,ЯРОСЛАВЛЬЗАКАЗЧИК,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ЯРОСЛАВЛЬЗАКАЗЧИК,0,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3589,0,45321,516648,2912,‹‹СЗ ‹‹СТРОЙ-НАДЕЖДА››,‹‹СЗ ‹‹СТРОЙ-НАДЕЖДА››,‹‹СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ‹‹СТРОЙ-НАДЕЖДА››,0,1,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df2 = pd.json_normalize(d)
df2

,errcode,data.id,data.pdId,data.developer.devId,data.developer.devShortCleanNm,data.developer.devShortNm,data.developer.devFullCleanNm,data.developer.problObjCnt,data.developer.buildObjCnt,data.developer.comissObjCnt,...,data.metro.colors,data.transportDistIndex,data.transportDistIndexValue,data.greenAreaIndexValue,data.complexShortNm,data.airQualityIndexValue,data.developer.bankruptStage.bankruptStageCd,data.developer.bankruptStage.bankruptStageDesc,data.developer.bankruptStage.bankruptLawUrl,data.developer.orgBankruptMsgDttm
0,0,44821,553544,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,44823,553544,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,42819,494660,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,42823,494660,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,42815,494660,11065,СЗ ГАРАНТИЯ,СЗ ГАРАНТИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ГАРАНТИЯ,0,27,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0,45570,565916,878,СЗ СИНАРА-ДЕВЕЛОПМЕНТ,СЗ СИНАРА-ДЕВЕЛОПМЕНТ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СИНАРА-ДЕВЕЛОПМЕНТ,0,7,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3996,0,38565,417066,10544,СЗ СИНЕРГИЯ,СЗ СИНЕРГИЯ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СИНЕРГИЯ,0,1,0,...,NaN,10 / 10,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3997,0,45015,507652,9694,СЗ СИНН ГРУПП,СЗ СИНН ГРУПП,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СИНН ГРУПП,0,1,2,...,[#D80707],4 / 10,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3998,0,46215,595689,14165,СЗ СИТИ,СЗ СИТИ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СИТИ,0,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3999,0,46214,595689,14165,СЗ СИТИ,СЗ СИТИ,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК СИТИ,0,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
frames = [df1, df2, df3]
dff = pd.concat(frames)
dff.reset_index(drop=True, inplace=True)
dff

,errcode,data.id,data.pdId,data.developer.devId,data.developer.devShortCleanNm,data.developer.devShortNm,data.developer.devFullCleanNm,data.developer.problObjCnt,data.developer.buildObjCnt,data.developer.comissObjCnt,...,data.developer.bankruptStage.bankruptStageDesc,data.developer.bankruptStage.bankruptLawUrl,data.developer.orgBankruptMsgDttm,data.metro.id,data.metro.name,data.metro.line,data.metro.color,data.metro.time,data.metro.isWalk,data.metro.colors
0,0,13391,28101,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,13397,28141,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,13398,28141,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,13399,28141,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,13383,28105,306,2МЕН ГРУПП,2МЕН ГРУПП,2МЕН ГРУПП,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10585,0,28071,99284,7344,ЯРКИЙ МИР,ЯРКИЙ МИР,ЯРКИЙ МИР,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10586,0,28074,96537,7344,ЯРКИЙ МИР,ЯРКИЙ МИР,ЯРКИЙ МИР,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10587,0,28072,96379,7344,ЯРКИЙ МИР,ЯРКИЙ МИР,ЯРКИЙ МИР,0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10588,0,44447,475093,2538,ЯРОСЛАВЛЬЗАКАЗЧИК,ЯРОСЛАВЛЬЗАКАЗЧИК,СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ЯРОСЛАВЛЬЗАКАЗЧИК,0,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10589,0,45321,516648,2912,‹‹СЗ ‹‹СТРОЙ-НАДЕЖДА››,‹‹СЗ ‹‹СТРОЙ-НАДЕЖДА››,‹‹СПЕЦИАЛИЗИРОВАННЫЙ ЗАСТРОЙЩИК ‹‹СТРОЙ-НАДЕЖДА››,0,1,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
writer = pd.ExcelWriter('output.xlsx')
dff.to_excel(writer)
writer.save()

In [111]:
dff.to_pickle('output.pkl')

In [112]:
import sqlite3
conn = sqlite3.connect('test_bd')

In [113]:
dff.to_sql('test_bd', conn, if_exists='replace', index = False)
conn.commit()
conn.close()

InterfaceError: Error binding parameter 50 - probably unsupported type.